id: A82F8E6AA
title: fD7DD
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:06.974394
  last_modified_at: 2022-05-27 17:54:06.974397
