id: A82F8E6AA
title: fAF3B
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:06.886325
  last_modified_at: 2022-05-27 17:54:06.886327
