id: A82F8E6AA
title: f9173
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:06.694822
  last_modified_at: 2022-05-27 17:54:06.694825
