id: A82F8E6AA
title: fF6DF
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:07.041658
  last_modified_at: 2022-05-27 17:54:07.041661
