id: A82F8E6AA
title: f7E9A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:06.546942
  last_modified_at: 2022-05-27 17:54:06.546945
