id: A82F8E6AA
title: fF886
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:07.044882
  last_modified_at: 2022-05-27 17:54:07.044885
