id: A82F8E6AA
title: fF25D
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 17:54:07.036121
  last_modified_at: 2022-05-27 17:54:07.036123
